version: '3.1'
services:
  meta-shift-bot:
    build: '.'
    restart: unless-stopped
    container_name: meta-shift-bot
    env_file:
      .env
    volumes:
      - data:/data
      - ./db.sqlite:/data/db.sqlite
volumes:
  data:
